#!/bin/bash

BASEDIR=$(dirname "$0")
cd "$BASEDIR"
/usr/bin/osascript -e "tell application \"Google Chrome\"" -e "activate" -e "make new window" -e "tell application \"System Events\"" -e "keystroke \"f\" using {control down, command down}" -e "end tell" -e "end tell" -e "open location \"http://localhost:8000/\""
python -m SimpleHTTPServer

